name: .NET

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MAINLINE: refs/heads/master
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: | 
        dotnet tool restore
        dotnet paket restore
    - name: Build
      run: dotnet build Feather.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Generate example site
      run: | 
        dotnet run -p ./src/Feather -- -C ./example
    - name: Deploy to gh-pages 🚀
      if: ${{ github.ref == env.MAINLINE }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: example/output/
